"""add password reset requests

Revision ID: 0c6532c19166
Revises: d878f7c42c4a
Create Date: 2026-08-03 14:33:39.848740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c6532c19166'
# error_logs(d878f7c42c4a)와 이 리비전이 둘 다 ad49607788dd에서 갈라져 나와, 두 브랜치를
# 합치는 순간 head가 2개가 됐다(alembic upgrade head가 실패한다). 서로 무관한 테이블
# 추가라 순서에 의미가 없으므로, 먼저 머지된 error_logs 뒤로 이어 붙여 사슬을 편다.
down_revision: Union[str, Sequence[str], None] = 'd878f7c42c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='정규화된(strip().lower()) 제출 이메일. 계정 존재와 무관하게 기록'),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='요청자 IP (request.client.host). 알 수 없으면 NULL — 이때 IP 축은 꺼진다'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('id'),
    comment='비밀번호 재설정 요청 이력 (rate limit 판정의 원장)'
    )
    op.create_index(op.f('ix_password_reset_requests_client_ip'), 'password_reset_requests', ['client_ip'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_email'), 'password_reset_requests', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_requests_email'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_client_ip'), table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    # ### end Alembic commands ###
