"""apply local time db default to audit timestamp columns

Revision ID: 0ee6a6f4d65d
Revises: 26e94d5983ab
Create Date: 2026-07-10 11:31:40.870818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee6a6f4d65d'
down_revision: Union[str, Sequence[str], None] = '26e94d5983ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping the IDENTITY server default on
    # users.id (model declares autoincrement=True without an explicit
    # sa.Identity(), which compare_server_default treats as "no default" vs
    # the live DB's actual GENERATED BY DEFAULT AS IDENTITY column). That's an
    # unrelated pre-existing mismatch, not something this migration should
    # touch, so it's intentionally removed here — this migration only changes
    # the audit timestamp columns' server default.
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('Asia/Seoul', now())"),
               existing_comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('Asia/Seoul', now())"),
               existing_comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)',
               existing_nullable=False)
    # ### end Alembic commands ###
