"""add audit logs

Revision ID: 46cafcd5ae36
Revises: dc4cc6d7949d
Create Date: 2026-07-30 17:27:51.178799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46cafcd5ae36'
down_revision: Union[str, Sequence[str], None] = 'dc4cc6d7949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='행위 코드 (AuditAction)'),
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='행위자 (FK: users.id, 계정 미상이면 NULL)'),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True, comment='행위 시점 이메일 스냅샷 (로그인 실패는 입력값 그대로)'),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True, comment='행위 시점 이름 스냅샷'),
    sa.Column('actor_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True, comment='요청 IP (IPv6까지)'),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='대상 종류 (AuditTarget)'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='대상 행 id (FK 아님)'),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True, comment='대상 이름 스냅샷 (프로젝트 제목·사용자 이름 등)'),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True, comment='호출한 HTTP 메서드'),
    sa.Column('http_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True, comment='호출한 실제 경로 (템플릿 아님)'),
    sa.Column('success_yn', sa.CHAR(length=1), server_default='Y', nullable=False, comment='성공 여부: Y | N'),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True, comment='한 줄 설명'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='활동 기록 (감사 로그, append-only)'
    )
    op.create_index('ix_audit_logs_created_at_id', 'audit_logs', ['created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
