"""recreate users and refresh_tokens tables with business-then-audit column order

Revision ID: 6b5040798a90
Revises: 6e54c5b37edf
Create Date: 2026-07-10 16:37:58.053651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b5040798a90'
down_revision: Union[str, Sequence[str], None] = '6e54c5b37edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 이전 마이그레이션(26e94d5983ab, 6e54c5b37edf)에서 이미 만든 이전 컬럼 순서의
    # 테이블을 먼저 지워야 한다 — PostgreSQL은 기존 컬럼 순서를 ALTER로 바꿀 수
    # 없어서, 새 순서(id, 업무 컬럼, 생성/수정 컬럼)로 다시 만드는 방식으로 처리한다.
    # FK 의존성 때문에 refresh_tokens(자식)를 users(부모)보다 먼저 지운다.
    op.drop_table('refresh_tokens')
    op.drop_table('users')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='로그인 이메일, UNIQUE'),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='argon2 해시 값 (평문 저장 금지)'),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='권한: member | admin (기본값 member)'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='가입 상태: pending | active | disabled | rejected (기본값 pending)'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='관리자가 승인/거절 처리한 일시'),
    sa.Column('approved_by', sa.BigInteger(), nullable=True, comment='승인/거절한 관리자 (FK: users.id 자기참조)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자 (FK: users.id 자기참조) — 자율가입은 NULL'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자 (FK: users.id 자기참조)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 계정 (자율 회원가입 + 관리자 승인)'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='리프레시 토큰 소유자 (FK: users.id)'),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='리프레시 토큰의 SHA-256 해시값 (원문 저장 안 함)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료 일시'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='폐기(회전/로그아웃) 처리 일시, 미폐기 시 NULL'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='리프레시 토큰 (회전/폐기 관리)'
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
