"""create refresh_tokens table

Revision ID: 6e54c5b37edf
Revises: 3cd856abfd65
Create Date: 2026-07-10 13:59:55.686700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e54c5b37edf'
down_revision: Union[str, Sequence[str], None] = '3cd856abfd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='리프레시 토큰 소유자 (FK: users.id)'),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='리프레시 토큰의 SHA-256 해시값 (원문 저장 안 함)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료 일시'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='폐기(회전/로그아웃) 처리 일시, 미폐기 시 NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='리프레시 토큰 (회전/폐기 관리)'
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping the IDENTITY server default on
    # users.id (model declares autoincrement=True without an explicit
    # sa.Identity(), which compare_server_default treats as "no default" vs
    # the live DB's actual GENERATED BY DEFAULT AS IDENTITY column). That's an
    # unrelated pre-existing mismatch, not something this migration should
    # touch (see 0ee6a6f4d65d for the same note), so it's intentionally
    # removed here — this migration only creates the refresh_tokens table.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
