"""create projects and stages

Revision ID: ac6e7626417d
Revises: 9cb1c3452965
Create Date: 2026-07-16 08:49:38.558323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac6e7626417d'
down_revision: Union[str, Sequence[str], None] = '9cb1c3452965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='소유자 (FK: users.id, 데이터 격리)'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='프로젝트 제목'),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='주제/프롬프트'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='상태: DRAFT | REVIEW | DONE'),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='현재 단계 이름 (예: script)'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='스타일·provider 선택 등 (JSONB)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='쇼츠 생성 프로젝트'
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='소속 프로젝트 (FK: projects.id)'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='단계 이름 (예: script)'),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='사용한 provider 이름 (예: fake)'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='상태: PENDING|RUNNING|NEEDS_REVIEW|APPROVED|FAILED'),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='산출물 (script는 대본 JSON, JSONB)'),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='실패 메시지 (성공/미실행 시 NULL)'),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False, comment='재생성 횟수 (재생성 시 +1)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='실행 시작 일시'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='실행 종료(성공/실패) 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='파이프라인 단계 (script|voice|captions|render)'
    )
    op.create_index(op.f('ix_stages_project_id'), 'stages', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_project_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
