"""add password reset codes

Revision ID: ad49607788dd
Revises: 46cafcd5ae36
Create Date: 2026-07-31 15:57:28.731566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad49607788dd'
down_revision: Union[str, Sequence[str], None] = '46cafcd5ae36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='코드 소유자 (FK: users.id)'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='6자리 인증코드(000000~999999) 문자열. 앞자리 0 보존, 해시 안 함'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료 일시 (발급 + 10분)'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='사용 완료 일시 (1회용). NULL이면 미사용'),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='검증 실패 누적. 한도 초과 시 코드 무효화'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='비밀번호 재설정 인증코드 (평문 저장, 1회용, 만료)'
    )
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
