"""create notices and notice reads

Revision ID: c6d1293bd755
Revises: ae9fe4100f24
Create Date: 2026-07-28 10:28:10.301215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6d1293bd755'
down_revision: Union[str, Sequence[str], None] = 'ae9fe4100f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='공지 제목'),
    sa.Column('body', sa.Text(), nullable=False, comment='본문 (일반 텍스트, 줄바꿈 그대로 표시)'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='상태: DRAFT | PUBLISHED (기본값 DRAFT)'),
    sa.Column('pinned_yn', sa.CHAR(length=1), server_default='N', nullable=False, comment='목록 상단 고정 여부: Y | N'),
    sa.Column('popup_yn', sa.CHAR(length=1), server_default='N', nullable=False, comment='메인 팝업 노출 여부: Y | N'),
    sa.Column('starts_at', sa.DateTime(), nullable=True, comment='게시 시작 일시 (DRAFT면 NULL)'),
    sa.Column('ends_at', sa.DateTime(), nullable=True, comment='게시 종료 일시 (NULL=무기한)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='소프트 삭제 일시 (NULL=미삭제)'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='삭제한 관리자 (FK: users.id)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='공지사항 (관리자 작성, 전체 사용자 열람)'
    )
    op.create_table('notice_reads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('notice_id', sa.BigInteger(), nullable=False, comment='읽은 공지 (FK: notices.id)'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='읽은 사용자 (FK: users.id)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'user_id', name='uq_notice_reads_notice_user'),
    comment='공지 읽음 기록 (행 존재 = 읽음, created_at = 읽은 시각)'
    )
    op.create_index(op.f('ix_notice_reads_notice_id'), 'notice_reads', ['notice_id'], unique=False)
    op.create_index(op.f('ix_notice_reads_user_id'), 'notice_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_reads_user_id'), table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_notice_id'), table_name='notice_reads')
    op.drop_table('notice_reads')
    op.drop_table('notices')
    # ### end Alembic commands ###
