"""add error logs

주의: feat/reset-rate-limit 브랜치의 0c6532c19166도 down_revision이 ad49607788dd다.
나중에 병합하는 쪽이 자기 down_revision을 먼저 병합된 리비전으로 바꿔야
head가 하나로 유지된다(안 그러면 alembic upgrade head가 Multiple heads로 실패한다).

Revision ID: d878f7c42c4a
Revises: ad49607788dd
Create Date: 2026-08-03 16:21:29.159551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd878f7c42c4a'
down_revision: Union[str, Sequence[str], None] = 'ad49607788dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='source + 예외 클래스 + 발생 위치. UPSERT 키. 메시지는 넣지 않는다'),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='발생 계층 — http·worker·pipeline·cleanup·email'),
    sa.Column('exc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='예외 클래스명'),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='앱 코드 기준 디렉토리/파일:줄. 트레이스백 전문은 저장하지 않는다'),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='마지막 발생의 예외 메시지 (200자로 자름)'),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='마지막 발생의 부가 정보. 호출자가 명시적으로 넘긴 값만'),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False, comment='누적 발생 횟수'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('id'),
    comment='에러 로그 (지문 단위 집계, 관리자 화면 없음)'
    )
    op.create_index(op.f('ix_error_logs_fingerprint'), 'error_logs', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_error_logs_source'), 'error_logs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_source'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_fingerprint'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
