"""create assets

Revision ID: e716148755d5
Revises: ac6e7626417d
Create Date: 2026-07-20 10:04:13.009330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e716148755d5'
down_revision: Union[str, Sequence[str], None] = 'ac6e7626417d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='기본키, BIGINT 자동 증가'),
    sa.Column('stage_id', sa.BigInteger(), nullable=False, comment='소속 단계 (FK: stages.id)'),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='산출물 종류: AUDIO (이후 SRT|VIDEO|IMAGE)'),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='STORAGE_PATH 기준 상대 경로'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='voice·size_bytes 등 부가정보 (JSONB)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Seoul', now())"), nullable=False, comment='수정일시 (로컬 벽시계 시각, 수정 시 갱신)'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='단계 산출물 파일 (음성·자막·영상)'
    )
    op.create_index(op.f('ix_assets_stage_id'), 'assets', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_stage_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
