-- Studio DB 스키마 DDL (문서용 참고 스냅샷)
--
-- 실제 스키마는 Alembic 마이그레이션(alembic/versions/*.py)이 기준(source of truth)이며,
-- 이 파일은 사람이 읽기 편하도록 같은 스키마를 순수 DDL로 정리한 것이다.
-- 이 파일을 직접 실행해서 DB를 만들지 않는다 (`uv run alembic upgrade head`를 사용할 것).
-- 테이블을 추가/변경할 때마다 이 파일과 docs/SCHEMA.md를 함께 갱신한다.
--
-- created_at/updated_at 기본값이 plain now()가 아니라 timezone('Asia/Seoul', now())인 이유:
-- DB 세션/서버 타임존이 UTC일 수 있어(예: 로컬 개발용 Postgres 컨테이너), now()를 그대로
-- naive TIMESTAMP 컬럼에 넣으면 UTC 벽시계 시각이 저장되어 로컬시간 저장 규칙이 깨진다.
-- 항상 Asia/Seoul 벽시계 시각으로 변환해서 저장하도록 명시적으로 timezone() 함수를 사용한다.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    password_hash VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    approved_at TIMESTAMP,
    approved_by BIGINT REFERENCES users (id),
    created_at TIMESTAMP NOT NULL DEFAULT (timezone('Asia/Seoul', now())),
    created_by BIGINT REFERENCES users (id),
    updated_at TIMESTAMP NOT NULL DEFAULT (timezone('Asia/Seoul', now())),
    updated_by BIGINT REFERENCES users (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

COMMENT ON TABLE users IS '사용자 계정 (자율 회원가입 + 관리자 승인)';
COMMENT ON COLUMN users.id IS '기본키, BIGINT 자동 증가';
COMMENT ON COLUMN users.email IS '로그인 이메일, UNIQUE';
COMMENT ON COLUMN users.password_hash IS 'argon2 해시 값 (평문 저장 금지)';
COMMENT ON COLUMN users.role IS '권한: member | admin (기본값 member)';
COMMENT ON COLUMN users.status IS '가입 상태: pending | active | disabled | rejected (기본값 pending)';
COMMENT ON COLUMN users.approved_at IS '관리자가 승인/거절 처리한 일시';
COMMENT ON COLUMN users.approved_by IS '승인/거절한 관리자 (FK: users.id 자기참조)';
COMMENT ON COLUMN users.created_at IS '생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)';
COMMENT ON COLUMN users.created_by IS '생성자 (FK: users.id 자기참조) — 자율가입은 NULL';
COMMENT ON COLUMN users.updated_at IS '수정일시 (로컬 벽시계 시각, 수정 시 갱신)';
COMMENT ON COLUMN users.updated_by IS '수정자 (FK: users.id 자기참조)';

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    token_hash VARCHAR NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT (timezone('Asia/Seoul', now())),
    created_by BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT (timezone('Asia/Seoul', now())),
    updated_by BIGINT
);

CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

COMMENT ON TABLE refresh_tokens IS '리프레시 토큰 (회전/폐기 관리)';
COMMENT ON COLUMN refresh_tokens.id IS '기본키, BIGINT 자동 증가';
COMMENT ON COLUMN refresh_tokens.user_id IS '리프레시 토큰 소유자 (FK: users.id)';
COMMENT ON COLUMN refresh_tokens.token_hash IS '리프레시 토큰의 SHA-256 해시값 (원문 저장 안 함)';
COMMENT ON COLUMN refresh_tokens.expires_at IS '만료 일시';
COMMENT ON COLUMN refresh_tokens.revoked_at IS '폐기(회전/로그아웃) 처리 일시, 미폐기 시 NULL';
COMMENT ON COLUMN refresh_tokens.created_at IS '생성일시 (로컬 벽시계 시각, Asia/Seoul 기준, timezone 정보 없음)';
COMMENT ON COLUMN refresh_tokens.created_by IS '생성자';
COMMENT ON COLUMN refresh_tokens.updated_at IS '수정일시 (로컬 벽시계 시각, 수정 시 갱신)';
COMMENT ON COLUMN refresh_tokens.updated_by IS '수정자';
